// Generated by CoffeeScript 1.10.0
(function() {
  var config;

  config = {
    dbPort: 27017,
    db: 'mongodb',
    dbIp: '192.168.137.88',
    dbName: 'wiki',
    dbUsername: '',
    dbPassword: '',
    isFirst: true
  };

  module.exports = config;

}).call(this);

//# sourceMappingURL=config.js.map
