// Generated by CoffeeScript 1.10.0
(function() {
  var ImageSchema, mongoose;

  mongoose = require('mongoose');

  ImageSchema = new mongoose.Schema({
    name: String,
    hashCode: String,
    url: String,
    meta: {
      createAt: {
        type: Date,
        "default": Date.now()
      },
      updateAt: {
        type: Date,
        "default": Date.now()
      }
    }
  });

  ImageSchema.pre('save', function(next) {
    if (this.isNew) {
      this.meta.createAt = this.meta.updateAt = Date.now();
    } else {
      this.meta.updateAt = Date.now();
    }
    next();
  });

  ImageSchema.statics = {
    fetch: function(cb) {
      return this.find({}).sort('meta.updateAt').exec(cb);
    },
    findBy: function(id, cb) {
      return this.find({
        _id: id
      }).sort('meta.updateAt').exec(cb);
    },
    findByHashCode: function(hashCode, cb) {
      return this.find({
        hashCode: hashCode
      }).sort('meta.updateAt').exec(cb);
    }
  };

  module.exports = ImageSchema;

}).call(this);

//# sourceMappingURL=image.js.map
