// Generated by CoffeeScript 1.10.0
(function() {
  var _, crypto, cryptoutil, fs, path;

  fs = require('fs');

  _ = require('underscore');

  crypto = require('crypto');

  path = require('path');

  hashAlgorithm(function(algorithm, filename, fun) {
    var shasum, txt;
    txt = fs.ReadStream(path.join(__dirname, '../doc/images/' + filename));
    shasum = crypto.createHash(algorithm);
    txt.on('data', function(d) {
      return shasum.update(d);
    });
    txt.on('end', function() {
      var d;
      d = shasum.digest('hex');
      return fun(d);
    });
  });

  hashAlgorithmMD5(filename, fun)(function() {
    return hashAlgorithm("md5", filename, fun);
  });

  cryptoutil = {
    md5: function(filepath, fun) {
      return hashAlgorithmMD5(filepath, fun);
    }
  };

  module.exports = cryptoutil;

}).call(this);

//# sourceMappingURL=cryptoutil.js.map
